apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: "{{ .Values.location_service.image }}:{{ default .Values.global.defaultTag .Values.location_service.tag }}"
          ports:
            - containerPort: 8080
