apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: "{{ .Values.recommendation_service.image }}:{{ default .Values.global.defaultTag .Values.recommendation_service.tag }}"
          ports:
            - containerPort: 8080
